In [ ]:
# Slicing 
# Shape
# dimension
# algebric function
# statis function
# Where() function


In [1]:
import numpy as np

In [2]:
l=[10,20,30]

In [3]:
arr=np.array(l)

In [4]:
arr

array([10, 20, 30])

In [6]:
arr.ndim

1

In [8]:
arr.shape

(3,)

In [9]:
l1=[[12,13,14],[15,16,17]]

In [10]:
arr1=np.array(l1)

In [11]:
print(arr1)

[[12 13 14]
 [15 16 17]]


In [12]:
arr1.shape

(2, 3)

In [13]:
# automatic number generations
# linspace  
# arange()
# randn()

In [14]:
ar1=np.arange(10)

In [15]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
ar2=np.arange(1,10)

In [17]:
print(ar2)

[1 2 3 4 5 6 7 8 9]


In [18]:
type(ar2)

numpy.ndarray

In [19]:
ar3=np.arange(1,10,2)

In [20]:
print(ar3)

[1 3 5 7 9]


In [22]:
li1=np.linspace(1,10)

In [23]:
print(li1)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [24]:
li2=np.linspace(1,100,50)

In [25]:
li2

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [28]:
li3=np.linspace(1,100,200,dtype=int)

In [27]:
li3

array([  1,   1,   1,   2,   2,   3,   3,   4,   4,   5,   5,   6,   6,
         7,   7,   8,   8,   9,   9,  10,  10,  11,  11,  12,  12,  13,
        13,  14,  14,  15,  15,  16,  16,  17,  17,  18,  18,  19,  19,
        20,  20,  21,  21,  22,  22,  23,  23,  24,  24,  25,  25,  26,
        26,  27,  27,  28,  28,  29,  29,  30,  30,  31,  31,  32,  32,
        33,  33,  34,  34,  35,  35,  36,  36,  37,  37,  38,  38,  39,
        39,  40,  40,  41,  41,  42,  42,  43,  43,  44,  44,  45,  45,
        46,  46,  47,  47,  48,  48,  49,  49,  50,  50,  51,  51,  52,
        52,  53,  53,  54,  54,  55,  55,  56,  56,  57,  57,  58,  58,
        59,  59,  60,  60,  61,  61,  62,  62,  63,  63,  64,  64,  65,
        65,  66,  66,  67,  67,  68,  68,  69,  69,  70,  70,  71,  71,
        72,  72,  73,  73,  74,  74,  75,  75,  76,  76,  77,  77,  78,
        78,  79,  79,  80,  80,  81,  81,  82,  82,  83,  83,  84,  84,
        85,  85,  86,  86,  87,  87,  88,  88,  89,  89,  90,  9

In [29]:
li4=np.linspace(1,100,300,endpoint=False)

In [30]:
li4

array([ 1.  ,  1.33,  1.66,  1.99,  2.32,  2.65,  2.98,  3.31,  3.64,
        3.97,  4.3 ,  4.63,  4.96,  5.29,  5.62,  5.95,  6.28,  6.61,
        6.94,  7.27,  7.6 ,  7.93,  8.26,  8.59,  8.92,  9.25,  9.58,
        9.91, 10.24, 10.57, 10.9 , 11.23, 11.56, 11.89, 12.22, 12.55,
       12.88, 13.21, 13.54, 13.87, 14.2 , 14.53, 14.86, 15.19, 15.52,
       15.85, 16.18, 16.51, 16.84, 17.17, 17.5 , 17.83, 18.16, 18.49,
       18.82, 19.15, 19.48, 19.81, 20.14, 20.47, 20.8 , 21.13, 21.46,
       21.79, 22.12, 22.45, 22.78, 23.11, 23.44, 23.77, 24.1 , 24.43,
       24.76, 25.09, 25.42, 25.75, 26.08, 26.41, 26.74, 27.07, 27.4 ,
       27.73, 28.06, 28.39, 28.72, 29.05, 29.38, 29.71, 30.04, 30.37,
       30.7 , 31.03, 31.36, 31.69, 32.02, 32.35, 32.68, 33.01, 33.34,
       33.67, 34.  , 34.33, 34.66, 34.99, 35.32, 35.65, 35.98, 36.31,
       36.64, 36.97, 37.3 , 37.63, 37.96, 38.29, 38.62, 38.95, 39.28,
       39.61, 39.94, 40.27, 40.6 , 40.93, 41.26, 41.59, 41.92, 42.25,
       42.58, 42.91,

In [31]:
li5=np.linspace(1,1000,10)

In [32]:
li5

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

In [41]:
li6=np.linspace(1,500,10,endpoint=False,retstep=True)

In [42]:
li6

(array([  1. ,  50.9, 100.8, 150.7, 200.6, 250.5, 300.4, 350.3, 400.2,
        450.1]), 49.9)

In [51]:
np.random.rand(10)

array([0.18099724, 0.10189994, 0.46221076, 0.26793836, 0.57689859,
       0.8599854 , 0.88440982, 0.25387953, 0.12373743, 0.287982  ])

In [44]:
np.random.randint(10)

3

In [45]:
np.random.randint(5,10)

5

In [47]:
np.random.randn(50)

array([ 0.62958515,  0.06145812, -0.94134743, -2.9367282 ,  1.49195184,
        0.39949145,  1.3666161 , -0.08058108, -0.34798306,  1.35951492,
       -1.78431006,  1.70158954,  0.26383638, -1.8781761 , -0.16491933,
        0.3152307 , -0.39405605, -1.91997821, -1.47290958, -0.05540914,
       -1.56741572, -0.42897489, -1.95308672, -0.1545965 ,  1.49341802,
        0.13269945, -0.11732272,  1.01584316,  0.41993786, -0.42978468,
       -1.33873065, -1.33374799, -1.89219639,  0.50968427,  0.36902039,
        0.58935538, -1.0345756 , -1.92494574, -0.04235649,  0.50668407,
       -0.60474644, -1.58340849, -0.19353849, -0.09529109, -2.30666499,
       -1.70572462,  0.20811529,  0.71075223,  0.67720239,  0.11077536])

In [52]:
mat=np.arange(1,11)

In [53]:
print(mat)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
# slicing and indexing


In [55]:
mat[0]

1

In [56]:
mat[::2]

array([1, 3, 5, 7, 9])

In [57]:
mat[1::3]

array([2, 5, 8])

In [58]:
len(mat)

10

In [59]:
mat1=mat.reshape(5,2)

In [60]:
print(mat1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [62]:
mat1.ndim

2

In [63]:
mat1.shape

(5, 2)

In [64]:
mat1.size

10

In [65]:
mat2=np.arange(1,13).reshape(3,4)

In [66]:
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
mat1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [68]:
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
l=list(np.arange(1,11))

In [70]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [71]:
print(mat)
print(l)

[ 1  2  3  4  5  6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [73]:
l[0:5]=[100,200,300,400,600]

In [74]:
print(l)

[100, 200, 300, 400, 600, 6, 7, 8, 9, 10]


In [75]:
mat[0:5]

array([1, 2, 3, 4, 5])

In [76]:
mat[0:5]=100

In [77]:
mat

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [78]:
l[::2]=[500,1000,1500,2000,2500]

In [79]:
print(l)

[500, 200, 1000, 400, 1500, 6, 2000, 8, 2500, 10]


In [80]:
l[::2]=100

TypeError: must assign iterable to extended slice

In [81]:
l_a=np.array(l)

In [82]:
l_a

array([ 500,  200, 1000,  400, 1500,    6, 2000,    8, 2500,   10])

In [83]:
l_a[::2]=999

In [84]:
print(l_a)

[999 200 999 400 999   6 999   8 999  10]


In [85]:
l1=[[10,20,30,40],[50,60,70,80],[90,100,110,120]]

In [86]:
print(l1)

[[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]


In [87]:
l1[0]

[10, 20, 30, 40]

In [108]:
l1[0:2,2:4]

TypeError: list indices must be integers or slices, not tuple

In [97]:
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
mat2[0]

array([1, 2, 3, 4])

In [99]:
mat2[1]

array([5, 6, 7, 8])

In [100]:
mat[2]

100

In [101]:
mat2[2]

array([ 9, 10, 11, 12])

In [102]:
mat2[0][0]

1

In [104]:
mat2[0:][::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
mat2[0:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [110]:
mat2[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [114]:
mat2[0::2,0::2]

array([[ 1,  3],
       [ 9, 11]])

In [115]:
# comperisions
mat2>4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [116]:
m_bool=mat2>4

In [117]:
print(mat2[m_bool])

[ 5  6  7  8  9 10 11 12]


In [118]:
mat2[mat2>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
l4=[[10],[10,20],[10,20,30],[10,20,30,40]]

In [120]:
print(l4)

[[10], [10, 20], [10, 20, 30], [10, 20, 30, 40]]


In [121]:
mat5=np.array(l4)

In [122]:
print(mat5)

[list([10]) list([10, 20]) list([10, 20, 30]) list([10, 20, 30, 40])]


In [128]:
l6=[[10,np.NaN,20],[np.NaN,30,40],[50,60,np.NaN]]

In [129]:
print(l6)

[[10, nan, 20], [nan, 30, 40], [50, 60, nan]]


In [130]:
mat7=np.array(l6)

In [131]:
print(mat7)

[[10. nan 20.]
 [nan 30. 40.]
 [50. 60. nan]]


In [133]:
mat7==None

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [134]:
np.NAN

nan

SyntaxError: invalid syntax (<ipython-input-135-32684f9b71b1>, line 1)

In [136]:
import pandas as pd

In [137]:
df=pd.DataFrame(mat7)

In [138]:
df

0     1     2
0  10.0   NaN  20.0
1   NaN  30.0  40.0
2  50.0  60.0   NaN

In [140]:
df.fillna(value=90)

0     1     2
0  10.0  90.0  20.0
1  90.0  30.0  40.0
2  50.0  60.0  90.0

nan

In [144]:
mat7

10