In [1]:
%timeit

In [2]:
%timeit
l=[]
for i in range(0,10000):
    l.append(i)


In [3]:
import numpy

In [4]:
# array
l_val=[10,20,30]
print(l_val)

[10, 20, 30]


In [5]:
arr=numpy.array(l_val)

In [6]:
print(arr)

[10 20 30]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
#indetity matrix
arr_ind=numpy.eye(3,dtype=float)
print(arr_ind)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
arr_ind1=numpy.eye(1)
print(arr_ind1)

[[1.]]


In [26]:
zero_mat=numpy.zeros([3,2],dtype=int)
print(zero_mat)

[[0 0]
 [0 0]
 [0 0]]


zero_mat=numpy.zeros((3,2))
print(zero_mat)

In [11]:
import numpy as np

In [12]:
one_mat=np.ones(1)

In [13]:
print(one_mat)

[1.]


In [14]:
one_mat1=np.ones(4)

In [15]:
print(one_mat1)

[1. 1. 1. 1.]


In [16]:
one_mat2=np.ones((4,4),dtype=int)

In [17]:
print(one_mat2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
zero_mat2=np.zeros((4,4),dtype=int)

In [19]:
zero_mat2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
 l=[2,4,5,6]

In [21]:
l_2d=np.array(l)

In [22]:
print(l_2d)

[2 4 5 6]


In [23]:
l_2d_1=np.array(l).reshape(2,2)

In [24]:
print(l_2d_1)

[[2 4]
 [5 6]]


In [25]:
l_2d_2=np.array(l).reshape(3,2)

ValueError: cannot reshape array of size 4 into shape (3,2)

In [ ]:
# numpy used to generate the number also

In [ ]:
#rand
#arange()
#linspace()

In [ ]:
arr_val=np.arange(10)

In [ ]:
arr_val

In [ ]:
arr_rand=np.arange(30,60)

In [ ]:
print(arr_rand)

In [ ]:
arr_rand

In [ ]:
alt_num=np.arange(1,100,2)

In [ ]:
print(alt_num)

In [ ]:
lin_spc=np.linspace(1,10)

In [ ]:
print(lin_spc)

In [ ]:
lin_spc1=np.linspace(1,100,5)

In [ ]:
print(lin_spc1)

In [ ]:
lin_spc2=np.linspace(1,100,10,endpoint=False)

In [ ]:
print(lin_spc2)

In [ ]:
ran_num=np.random.rand(10)

In [ ]:
print(ran_num)

In [ ]:
ran_num_int=np.random.randint(1,1000000,10)

In [ ]:
print(ran_num_int)

In [ ]:
np.random.seed(10)

In [ ]:
np.random.seed(42)
ran_num=np.random.rand(10)
print(ran_num)