In [1]:
import numpy as np

In [2]:
l=[10,20,30]
print(l)

[10, 20, 30]


In [3]:
print(type(l))

<class 'list'>


In [4]:
arr=np.array(l)

In [5]:
print(arr)

[10 20 30]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

1

In [8]:
arr.shape

(3,)

In [9]:
arr=np.arange(10)

In [10]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
arr1=np.arange(0,30).reshape(10,3)

In [20]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [13]:
arr2=np.arange(2,17,2)

In [14]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [15]:
arr2.reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [35]:
arr2=np.linspace(0,100,27,endpoint='false',dtype="int").reshape(3,3,3)

In [36]:
arr2

array([[[  0,   3,   7],
        [ 11,  15,  19],
        [ 23,  26,  30]],

       [[ 34,  38,  42],
        [ 46,  50,  53],
        [ 57,  61,  65]],

       [[ 69,  73,  76],
        [ 80,  84,  88],
        [ 92,  96, 100]]])

In [37]:
arr2.shape

(3, 3, 3)

In [38]:
arr2.ndim

3

In [50]:
arr3=np.linspace(0,3,200,endpoint="false",dtype="int").reshape(10,10,2)

In [47]:
arr3

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 

In [61]:
arr4=np.random.rand(1,10)

In [62]:
arr4

array([[0.94594832, 0.07456888, 0.04411255, 0.99226499, 0.88758621,
        0.80798945, 0.83521178, 0.4911325 , 0.63702298, 0.47461504]])

In [72]:
np.random.seed(1)
arr5=np.random.randint(50)

In [80]:
arr5

37

In [108]:
np.random.seed(42)
arr6=np.random.rand(10)
arr7=arr6.copy()

In [110]:
arr7.reshape(1,1,10)

array([[[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
         0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]]])

In [106]:
arr6

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [102]:
arr6

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [114]:
np.random.randint(100)

21

In [196]:
arr8=np.random.rand(2,3,2,1)

In [197]:
arr8

array([[[[0.73590461],
         [0.8481281 ]],

        [[0.12277689],
         [0.87644408]],

        [[0.64292556],
         [0.70394614]]],


       [[[0.910624  ],
         [0.62476127]],

        [[0.33586586],
         [0.82510733]],

        [[0.36305921],
         [0.03422811]]]])

In [152]:
l=[10,20,30,40,50,60,70,80]

In [153]:
arr=np.array(l)

In [154]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [155]:
arr1=arr.reshape(4,2)

In [156]:
arr1

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [157]:
arr1[0]

array([10, 20])

In [158]:
arr1[0:4,1]

array([20, 40, 60, 80])

In [159]:
arr1[0::]

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [160]:
arr1[1:,1]

array([40, 60, 80])

In [176]:
arr2=arr1[2:4]
    

In [181]:
arr3=arr2[0][0]

In [182]:
arr3

50

In [183]:
arr4=arr2[1][1]

In [184]:
arr4

80

In [185]:
arr3+arr4

130

In [192]:
print(arr3,arr4 )

50 80


In [202]:
arr1=np.arange(1,11).reshape(5,2)

In [203]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [206]:
arr2=np.arange(11,21).reshape(5,2)

In [207]:
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [215]:
arr3=np.concatenate([arr1,arr2],axis=1)

In [216]:
arr3

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [217]:
arr4=arr3.copy()

In [218]:
arr4

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [227]:
arr5=np.hstack(arr4,2)

TypeError: hstack() takes 1 positional argument but 2 were given

In [226]:
arr5

array([ 1,  2, 11, 12,  3,  4, 13, 14,  5,  6, 15, 16,  7,  8, 17, 18,  9,
       10, 19, 20])

In [232]:
a1=np.vsplit(arr2,5)

In [233]:
a1

[array([[11, 12]]),
 array([[13, 14]]),
 array([[15, 16]]),
 array([[17, 18]]),
 array([[19, 20]])]

In [234]:
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [235]:
a1[0]

array([[11, 12]])

In [236]:
a1[2]

array([[15, 16]])

In [237]:
a1

[array([[11, 12]]),
 array([[13, 14]]),
 array([[15, 16]]),
 array([[17, 18]]),
 array([[19, 20]])]

In [238]:
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [239]:
a2=np.hsplit(arr2,2)

In [240]:
a2

[array([[11],
        [13],
        [15],
        [17],
        [19]]), array([[12],
        [14],
        [16],
        [18],
        [20]])]

In [241]:
l=[100,200,300,400,500,600,700,800]

In [242]:
l

[100, 200, 300, 400, 500, 600, 700, 800]

In [252]:
arr1=np.array(l)

In [253]:
arr1

array([100, 200, 300, 400, 500, 600, 700, 800])

In [259]:
dtype(arr1)

TypeError: 'numpy.ndarray' object is not callable

In [260]:
arr1

array([100, 200, 300, 400, 500, 600, 700, 800])

In [261]:
dtype(arr1)

TypeError: 'numpy.ndarray' object is not callable

In [262]:
arr1

array([100, 200, 300, 400, 500, 600, 700, 800])

In [268]:
arr2=np.where(arr1==400,20,100)

In [266]:
arr2

array([100, 100, 100, 120, 100, 100, 100, 100])

In [269]:
arr1

array([100, 200, 300, 400, 500, 600, 700, 800])

In [271]:
arr11=arr1.reshape(4,2)

In [272]:
arr11

array([[100, 200],
       [300, 400],
       [500, 600],
       [700, 800]])

In [276]:
arr111=np.where(arr11==400,"true","false")

In [277]:
arr111

array([['false', 'false'],
       ['false', 'true'],
       ['false', 'false'],
       ['false', 'false']], dtype='<U5')

In [280]:
arr12=np.where(arr111=="true","false","false")

In [281]:
arr12

array([['false', 'false'],
       ['false', 'false'],
       ['false', 'false'],
       ['false', 'false']], dtype='<U5')

In [284]:
arr111=="true"

array([[False, False],
       [False,  True],
       [False, False],
       [False, False]])

In [285]:
arr111

array([['false', 'false'],
       ['false', 'true'],
       ['false', 'false'],
       ['false', 'false']], dtype='<U5')

In [286]:
arr111=="false"

array([[ True,  True],
       [ True, False],
       [ True,  True],
       [ True,  True]])

In [287]:
arr1

array([100, 200, 300, 400, 500, 600, 700, 800])

In [288]:
arr11

array([[100, 200],
       [300, 400],
       [500, 600],
       [700, 800]])

In [289]:
arr11==400

array([[False, False],
       [False,  True],
       [False, False],
       [False, False]])

In [290]:
#statistical 

In [291]:
arr11

array([[100, 200],
       [300, 400],
       [500, 600],
       [700, 800]])

In [303]:
ar1=np.mean(arr11,axis=1)

In [304]:
ar1

array([150., 350., 550., 750.])

In [294]:
ar2=np.max(arr11)

In [295]:
ar2

800

In [296]:
np.min(arr11)

100

In [305]:
arr3

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [306]:
np.mean(arr3,axis=0)

array([ 5.,  6., 15., 16.])

In [307]:
np.mean(arr3,axis=1)

array([ 6.5,  8.5, 10.5, 12.5, 14.5])

In [308]:
arr2

array([100, 100, 100,  20, 100, 100, 100, 100])

In [309]:
arr3

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [310]:
arr4

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [316]:
np.sum(arr3,axis=1)

array([26, 34, 42, 50, 58])

In [317]:
arr3

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [318]:
arr31=arr3.reshape(5,2,2)

In [319]:
arr31

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [328]:
arr311=np.ravel(arr31)

In [329]:
arr311

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19,  2,  4,  6,  8, 10, 12, 14,
       16, 18, 20])

In [330]:
l

[100, 200, 300, 400, 500, 600, 700, 800]

In [331]:
l1=([10],[20],[30],[40],[50])

In [333]:
l1

([10], [20], [30], [40], [50])

In [334]:
l1_ravel=np.ravel(l1)

In [336]:
l1_ravel

array([10, 20, 30, 40, 50])

In [337]:
arr2

array([100, 100, 100,  20, 100, 100, 100, 100])

In [338]:
arr4

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [339]:
arr12=arr4.T

In [340]:
arr12

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [11, 13, 15, 17, 19],
       [12, 14, 16, 18, 20]])

In [341]:
arr4.transpose()

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [11, 13, 15, 17, 19],
       [12, 14, 16, 18, 20]])

In [342]:
arr3

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [343]:
arr3.transpose()

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [11, 13, 15, 17, 19],
       [12, 14, 16, 18, 20]])

In [344]:
arr3

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [346]:
arr41=np.transpose(arr3)

In [347]:
arr41

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [11, 13, 15, 17, 19],
       [12, 14, 16, 18, 20]])

In [348]:
arr122=np.dot(arr41,arr3)

In [349]:
arr122

array([[ 165,  190,  415,  440],
       [ 190,  220,  490,  520],
       [ 415,  490, 1165, 1240],
       [ 440,  520, 1240, 1320]])

In [355]:
arr411=arr4.transpose()

In [356]:
arr411

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [11, 13, 15, 17, 19],
       [12, 14, 16, 18, 20]])

In [351]:
arr3

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [353]:
np.multiply(arr41,arr3)

ValueError: operands could not be broadcast together with shapes (4,5) (5,4) 

In [357]:
arr31=np.multiply(arr41,arr3)

ValueError: operands could not be broadcast together with shapes (4,5) (5,4) 

In [360]:
arr=np.array(10,30,50,70)

ValueError: only 2 non-keyword arguments accepted